title: FUUN.FUN
baseurl: ""
url: "https://fuun.fun"

lang: zh-CN

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

seo:
  - tagline: 收集各种有趣
  - description: 收集一些有趣或无聊的网站，帮你发现新鲜事物

compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]